-- SET filePath = ${YEAR}.csv;
-- SET tableName = f_${YEAR};

-- CREATE EXTERNAL TABLE IF NOT EXISTS ${hiveconf:tableName} (year INT, month INT, dayofmonth INT, dayofweek INT, deptime INT,crsdeptime INT,arrtime INT,crsarrtime INT,uniquecarrier STRING,flightnum INT,tailnum STRING,actualelapsedtime INT,crselapsedtime INT,airtime INT,arrdelay INT,depdelay INT,origin STRING,dest STRING,distance INT,taxiin INT,taxiout INT,cancelled INT,cancellationcode STRING,diverted INT,carrierdelay INT,weatherdelay INT,nasdelay INT,securitydelay INT,lateaircraftdelay INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' tblproperties("skip.header.line.count"="1");
-- LOAD DATA LOCAL INPATH `${hiveconf:filePath}` OVERWRITE INTO TABLE ${hiveconf:tableName}; 

CREATE EXTERNAL TABLE IF NOT EXISTS f_1997 (year INT, month INT, dayofmonth INT, dayofweek INT, deptime INT,crsdeptime INT,arrtime INT,crsarrtime INT,uniquecarrier STRING,flightnum INT,tailnum STRING,actualelapsedtime INT,crselapsedtime INT,airtime INT,arrdelay INT,depdelay INT,origin STRING,dest STRING,distance INT,taxiin INT,taxiout INT,cancelled INT,cancellationcode STRING,diverted INT,carrierdelay INT,weatherdelay INT,nasdelay INT,securitydelay INT,lateaircraftdelay INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' tblproperties("skip.header.line.count"="1");
LOAD DATA LOCAL INPATH "1997.csv" OVERWRITE INTO TABLE f_1997;
CREATE EXTERNAL TABLE IF NOT EXISTS f_2002 (year INT, month INT, dayofmonth INT, dayofweek INT, deptime INT,crsdeptime INT,arrtime INT,crsarrtime INT,uniquecarrier STRING,flightnum INT,tailnum STRING,actualelapsedtime INT,crselapsedtime INT,airtime INT,arrdelay INT,depdelay INT,origin STRING,dest STRING,distance INT,taxiin INT,taxiout INT,cancelled INT,cancellationcode STRING,diverted INT,carrierdelay INT,weatherdelay INT,nasdelay INT,securitydelay INT,lateaircraftdelay INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' tblproperties("skip.header.line.count"="1");
LOAD DATA LOCAL INPATH "2002.csv" OVERWRITE INTO TABLE f_2002;
CREATE EXTERNAL TABLE IF NOT EXISTS f_2005 (year INT, month INT, dayofmonth INT, dayofweek INT, deptime INT,crsdeptime INT,arrtime INT,crsarrtime INT,uniquecarrier STRING,flightnum INT,tailnum STRING,actualelapsedtime INT,crselapsedtime INT,airtime INT,arrdelay INT,depdelay INT,origin STRING,dest STRING,distance INT,taxiin INT,taxiout INT,cancelled INT,cancellationcode STRING,diverted INT,carrierdelay INT,weatherdelay INT,nasdelay INT,securitydelay INT,lateaircraftdelay INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' tblproperties("skip.header.line.count"="1");
LOAD DATA LOCAL INPATH "2005.csv" OVERWRITE INTO TABLE f_2005;
CREATE EXTERNAL TABLE IF NOT EXISTS f_2006 (year INT, month INT, dayofmonth INT, dayofweek INT, deptime INT,crsdeptime INT,arrtime INT,crsarrtime INT,uniquecarrier STRING,flightnum INT,tailnum STRING,actualelapsedtime INT,crselapsedtime INT,airtime INT,arrdelay INT,depdelay INT,origin STRING,dest STRING,distance INT,taxiin INT,taxiout INT,cancelled INT,cancellationcode STRING,diverted INT,carrierdelay INT,weatherdelay INT,nasdelay INT,securitydelay INT,lateaircraftdelay INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' tblproperties("skip.header.line.count"="1");
LOAD DATA LOCAL INPATH "2006.csv" OVERWRITE INTO TABLE f_2006;
CREATE EXTERNAL TABLE IF NOT EXISTS f_2007 (year INT, month INT, dayofmonth INT, dayofweek INT, deptime INT,crsdeptime INT,arrtime INT,crsarrtime INT,uniquecarrier STRING,flightnum INT,tailnum STRING,actualelapsedtime INT,crselapsedtime INT,airtime INT,arrdelay INT,depdelay INT,origin STRING,dest STRING,distance INT,taxiin INT,taxiout INT,cancelled INT,cancellationcode STRING,diverted INT,carrierdelay INT,weatherdelay INT,nasdelay INT,securitydelay INT,lateaircraftdelay INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' tblproperties("skip.header.line.count"="1");
LOAD DATA LOCAL INPATH "2007.csv" OVERWRITE INTO TABLE f_2007;