-- Sample Table
DROP TABLE IF EXISTS samples;
CREATE TABLE samples AS select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_2007 as f where f.cancelled = 0 AND (f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;
INSERT INTO TABLE samples select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_2007 as f where f.cancelled = 0 AND NOT(f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;
INSERT INTO TABLE samples select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_2006 as f where f.cancelled = 0 AND (f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;
INSERT INTO TABLE samples select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_2006 as f where f.cancelled = 0 AND NOT(f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;
INSERT INTO TABLE samples select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_2005 as f where f.cancelled = 0 AND (f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;
INSERT INTO TABLE samples select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_2005 as f where f.cancelled = 0 AND NOT(f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;
INSERT INTO TABLE samples select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_2002 as f where f.cancelled = 0 AND (f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;
INSERT INTO TABLE samples select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_2002 as f where f.cancelled = 0 AND NOT(f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;
INSERT INTO TABLE samples select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_1997 as f where f.cancelled = 0 AND (f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;
INSERT INTO TABLE samples select f.dayofmonth, f.dayofweek, f.deptime, f.crsdeptime, f.uniquecarrier, f.flightnum, f.tailnum, f.actualelapsedtime, f.crselapsedtime, f.origin, f.dest, f.distance, (f.arrdelay>0 OR f.depdelay>0) as delayed from f_1997 as f where f.cancelled = 0 AND NOT(f.arrdelay>0 OR f.depdelay>0) AND f.actualelapsedtime != float('NaN') distribute by rand() sort by rand() limit 20000;;

